// 22 tags from PRD Appendix 20.2
export const TAGS: string[] = [
  "24/7",
  "Pet Friendly",
  "Parking Available",
  "Wi-Fi Available",
  "Live Music",
  "Outdoor Seating",
  "LGBTQ+ Friendly",
  "Happy Hour",
  "Wheelchair Accessible",
  "Hookah / Shisha",
  "Dance Floor",
  "VIP Area",
  "Food Available",
  "Craft Beer",
  "Rooftop",
  "Family Friendly",
  "Student Discount",
  "Ladies Night",
  "Sports Screening",
  "Pool Table",
  "Darts",
  "Board Games",
];
